update deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,20 +22,46 @@ jobs:
       env:
         NODE_ENV: production
 
+    - name: Install wrangler
+      run: npm install -g wrangler
+
+    - name: Check and Create KV Namespace
+      env:
+        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
+        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
+      run: |
+        KV_NAMESPACE="KV_STATUS_PAGE"
+        echo "Checking for KV namespace: $KV_NAMESPACE"
+        LIST_OUTPUT=$(wrangler kv namespace list)
+        echo "KV namespace list output: $LIST_OUTPUT"
+        
+        KV_ID=$(echo "$LIST_OUTPUT" | jq -r '.[] | select(.title == "cf-workers-status-page-'$KV_NAMESPACE'") | .id')
+        
+        if [ -z "$KV_ID" ]; then
+            echo "KV namespace $KV_NAMESPACE does not exist. Creating..."
+            CREATE_OUTPUT=$(wrangler kv namespace create "$KV_NAMESPACE")
+            echo "Create KV namespace output: $CREATE_OUTPUT"
+            KV_ID=$(echo "$CREATE_OUTPUT" | sed -n 's/.*id = "\([^"]*\)".*/\1/p')
+            
+            if [ -z "$KV_ID" ]; then
+                echo "Failed to extract KV ID. Full output: $CREATE_OUTPUT"
+                exit 1
+            fi
+            
+            echo "KV namespace $KV_NAMESPACE created successfully with ID: $KV_ID"
+        else
+          echo "KV namespace $KV_NAMESPACE already exists with ID: $KV_ID"
+        fi
+        echo "KV_ID=$KV_ID" >> $GITHUB_ENV
+
+
     - name: Publish
       uses: cloudflare/wrangler-action@v3
       with:
         apiToken: ${{ secrets.CF_API_TOKEN }}
         preCommands: |
-          npm install -g wrangler
-          wrangler kv:namespace create KV_STATUS_PAGE || true
-          echo $(wrangler kv namespace list)
-          LIST_OUTPUT=$(wrangler kv namespace list)
-          echo "$LIST_OUTPUT"
-          KV_NAMESPACE_ID=$(wrangler kv namespace list | jq -r '.[] | select(.title == "cf-workers-status-page-KV_STATUS_PAGE") | .id')
-          echo "$KV_NAMESPACE_ID"
           echo "[env.production]" >> wrangler.toml
-          echo "kv_namespaces = [{binding=\"KV_STATUS_PAGE\", id=\"${KV_NAMESPACE_ID}\"}]" >> wrangler.toml
+          echo "kv_namespaces = [{binding=\"KV_STATUS_PAGE\", id=\"$KV_ID\"}]" >> wrangler.toml
           cat wrangler.toml
         postCommands: |
           yarn kv-gc
